version: "2.4"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./script:/app
    environment:
      - MAPBOX_ACCESS_TOKEN=sk.eyJ1Ijoic2hhbGluaTEyOTciLCJhIjoiY2wwZ2lsNnlkMTM4bDNjazZvc3VzNHc1OCJ9.LdWiqSVbOpUkWJYEp6QY2A
      - MAPBOX_HOST=api.mapbox.com
    command: [ "./app/wait-for-postgres.sh","postgres","python", "./app/geo.py"]

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    restart: on-failure
    ports:
      - "6432:5432"
    volumes:
      - ./sql:/opt/sql
      - ./docker/postgres:/opt/refresh
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: geovisualizer
      POSTGRES_PASSWORD: 
      POSTGRES_USER: postgres
volumes:
  postgres-data:
